version: '3.7'

services:
  database_beka: 
    image: postgres
    container_name:  beka-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=beka
      - POSTGRES_PASSWORD=beka
      - POSTGRES_DB=beka
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: beka-api
    tty: true
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/app
    network_mode: host
    depends_on:
      - database_beka
    
  Redis_beka:
    image: sameersbn/redis:4.0.9-3
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/var/lib/redis
    restart: always

volumes:
  pgdata:
    